import type { Metadata } from "next";
import localFont from "next/font/local";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";
import CustomCursor from "@/components/cursor/CustomCursor";

const bosch = localFont({
  src: "./fonts/Bosch.woff",
  variable: "--font-bosch",
  weight: "100 900",
});
const Poppins = localFont({
  src: "./fonts/Poppins.woff",
  variable: "--font-poppins",
  weight: "500",
});

const IBMPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Home | Kaara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBMPlexSans.className} ${bosch.variable} ${Poppins.variable} antialiased`}
      >
        <Header />
        <div>
          <CustomCursor />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
